name: SentryRelease

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '15.x'
      - run: npm install
      - run: env GIT_COMMIT_HASH=${{github.sha}} npm run build-nocrossenv --if-present
      - name: Create a Sentry.io release
        uses: tclindner/sentry-releases-action@v1.2.0
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: meteocool
          SENTRY_PROJECT: web
        with:
          tagName: ${{github.sha}}
          environment: production
          releaseNamePrefix:
          sourceMapOptions: '{"include": ["dist"]}'
