name: SentryRelease

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  createSentryRelease:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Create a Sentry.io release
        uses: tclindner/sentry-releases-action@v1.2.0
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: meteocool
          SENTRY_PROJECT: web
        with:
          tagName: ${GITHUB_SHA::8}
          environment: prod
          releaseNamePrefix: meteocool-web-
          sourceMapOptions: '{"include": ["build"]}'
